version: "3.9"

services:
  enhance-ticket:
    build: .
    ports:
      - "4747:4747"
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml

  ngrok:
    image: ngrok/ngrok:latest
    command: http enhance-ticket:4747
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - enhance-ticket
